/**
 * Converts a WebAuthn credential ID from Base64URL encoding into a Uint8Array.
 *
 * WebAuthn credential IDs are binary values generated by the authenticator.
 * When transmitted or stored (e.g., in JSON or databases), they are typically
 * encoded using Base64URL. However, the WebAuthn browser APIs expect the
 * credential ID to be provided as raw binary data (`Uint8Array`).
 *
 * This function performs the following steps:
 *
 * 1. Converts the Base64URL string into standard Base64 by replacing
 *    URL-safe characters (`-` → `+`, `_` → `/`).
 * 2. Decodes the Base64 string into its binary representation using `atob`.
 * 3. Converts the decoded binary string into a `Uint8Array` of byte values.
 *
 * The resulting `Uint8Array` can be used directly in WebAuthn operations,
 * such as the `allowCredentials` list passed to `navigator.credentials.get()`.
 *
 * @param credentialId - The credential ID encoded as a Base64URL string
 * (commonly stored in a database or returned by the server).
 *
 * @returns A Uint8Array containing the raw credential ID bytes.
 *
 * @example
 * const credentialId = "AbCdEf123...";
 *
 * const idBytes = credentialIdToUint8Array(credentialId);
 *
 * const assertion = await navigator.credentials.get({
 *   publicKey: {
 *     challenge,
 *     allowCredentials: [
 *       {
 *         id: idBytes,
 *         type: "public-key"
 *       }
 *     ]
 *   }
 * });
 */
export declare function credentialIdToUint8Array(credentialId: string): Uint8Array<ArrayBuffer>;
